### ISSUE TITLE
positive area 

### ISSUE THREAD

**Issue by luqioayun** [nerminsamet/ppdet#2]
the positive area in the groundtruth is labeled as "1" or labeled as heatmap like "cornernet"? 

Thanks a lot

**Comment by nerminsamet** [comment]
Hi luqioayun,

we do **not** label the positive area in the ground-truth as heatmap, it is labelled as 1.

**Comment by luqioayun** [comment]
> Hi luqioayun,
> 
> we do **not** label the positive area in the ground-truth as heatmap, it is labelled as 1.

thanks a lot~
i have another question that how do you dedide the positive area? is it the 0.4*groundtruth box? or it is adaptive?

**Comment by nerminsamet** [comment]
The positive area  is not adaptive. We experimented between 1.0*ground-truth - 0.2*ground-truth box. And 0.4*ground-truth yielded the best performance, that's why we used it in our final setup.

**Comment by luqioayun** [comment]
> The positive area is not adaptive. We experimented between 1.0_ground-truth - 0.2_ground-truth box. And 0.4*ground-truth yielded the best performance, that's why we used it in our final setup.

ok, got it, thanks~
may be the paper is the same as "FoveaBox: Beyound Anchor-Based Object Detection". the detection head like this?
![image](https://user-images.githubusercontent.com/39177525/91424081-ef3be700-e88b-11ea-8e14-4fb90f00f6d1.png)

**Comment by nerminsamet** [comment]
Yes, like FoveaBox, FSAF and Guided Anchoring,  PPDet also follows region based discrete labeling strategy (e.g. positive region, ignore region and negative area).

**Comment by luqioayun** [comment]
> Yes, like FoveaBox, FSAF and Guided Anchoring, PPDet also follows region based discrete labeling strategy (e.g. positive region, ignore region and negative area).

thank you very much, I have got the above in your paper.
so, what is the defference between the paper and "FoveaBox: Beyound Anchor-Based Object Detection" which "positive area" is also the 0.4_ground-truth? Maybe the defference is regression about coordinate (x, y)?

**Comment by nerminsamet** [comment]
Our main contribution is that we apply sum-pooling to reduce the contribution of non-nondiscriminatory features during training, and also we apply a similar sum-pooling strategy at inference. You could find all the details in our paper.
