### ISSUE TITLE
"Segmentation fault" at training start

### ISSUE THREAD

**Issue by victoic** [nerminsamet/ppdet#4]
Hello, I'm trying to train on a custom dataset using COCO format of annotations. 
However, right after the `"INFO - Start running (...)"` and `"INFO - workflow (...)"` lines I get `"Segmentation fault"` and the proccess is stopped. 
What does that mean?

Edit: It might be important to explicit that other than the changes in the config to accomodate my file names, nothing is changed.

**Comment by giddyyupp** [comment]
Hi,
actually we need little bit more info to understand the reason :)
we build on top of mmdetection code base, so it could be helpful to check similar errors in the issues of mmdetection.
For instance, I find a similar one here: https://github.com/open-mmlab/mmdetection/issues/4217#issuecomment-739138129 
also here: https://github.com/open-mmlab/mmdetection/issues/1980
